
spring:
  application:
    name: zuul

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/erueka


management:
  endpoints:
    web:
      exposure:
        include: "*"

zuul:
  routes:
    goods-ui: /goods/**
    books-ui: /books/**